version: "3.7"

networks:
  mern-stack-net:
    driver: bridge

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: client
    networks:
      - mern-stack-net
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    command: bash -c "npm start"
    depends_on:
      - server
    stdin_open: true
    tty: true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "4000"
    ports:
      - 4000:4000
    container_name: server
    networks:
      - mern-stack-net
    volumes:
      - ./server/:/usr/app/
    command: bash -c "npm run dev"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - "27017"
    container_name: mongo-db
    hostname: db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db
  dbclient:
    image: mongoclient/mongoclient
    ports:
      - '3300:3000'
    container_name: mongo-client
    hostname: mongoclient
    depends_on:
      - db
    networks:
      - mern-stack-net

  

volumes:
  mongo-data:
    external:
      name: mongo_external
  client-data:
