version: "3.7"

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: client
    networks:
      - mern-stack-net
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    command: bash -c "npm start"
    depends_on:
      - server
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    container_name: server
    networks:
      - mern-stack-net
    volumes:
      - ./server/:/usr/app/
    command: bash -c "npm run dev"
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-stack-net:
    driver: bridge

volumes:
  mongo-data:
    external:
      name: mongo_external
